// Demo code to communicate with the server in JavaScript

// Function to call the web api through AJAX
var getResults = function (inputs) {
    var result;
    var txt2Parse;
    jQuery.ajax({
        type: 'POST',
        data: inputs,
        dataType: '',
        url: 'http://trends-tti.tamu.edu/AJAXCalculate.asmx/GetJSONResults',
        success: function (data) {
            txt2Parse = $(data).text();
            result = eval('(' + txt2Parse + ')');
        },
        async: false
    });
    return result;
};


// Example inputs
var Inputs = {
    "PersonalGrowthAssumptions":"GrowthAssumption4",
        "FuelEfficiencyPersonal":"average",
        "FuelEfficiencyCommercial":"average",
        "NewCapacity":"Yes",
        "AdditionalCapacity":"12.0",
        "AdditionalCapacityBegins":"2016",
        "AdditionalCapacityEnds":"2016",
        "TxDOTMaintenance":"Yes",
        "MaintenanceEstimate":"90",
        "OtherExpenseIncreases":"No",
        "ExpensePlan":"1",
        "ExpenseBuild":"1",
        "ExpenseMaintenance":"1",
        "ExpenseUse":"1",
        "ExpenseManage":"1",
        "ExpenseOtherAgencies":"1",
        "ExpenseContributions":"1",
        "ExpenseIncreases":"No",
        "ExpenseCat1":"1",
        "ExpenseCat5":"1",
        "ExpenseCat6":"1",
        "ExpenseCat7":"1",
        "ExpenseCat8":"1",
        "ExpenseCat9":"1",
        "ExpenseCat10":"1",
        "ExpenseCat11":"1",
        "StateGasTax":"Yes",
        "StateGasTaxRate":"50",
        "StateGasTaxYear":"2016",
        "StateGasTax2":"No",
        "StateGasTaxRate2":"0",
        "StateGasTaxYear2":"2016",
        "StateDieselTax":"No",
        "StateDieselTaxRate":"0",
        "StateDieselTaxYear":"2016",
        "StateDieselTax2":"No",
        "StateDieselTaxRate2":"0",
        "StateDieselTaxYear2":"2016",
        "FederalGasTax":"Yes",
        "FederalGasTaxRate":"50",
        "FederalGasTaxYear":"2016",
        "FederalGasTax2":"No",
        "FederalGasTaxRate2":"0",
        "FederalGasTaxYear2":"2019",
        "FederalDieselTax":"No",
        "FederalDieselTaxRate":"0",
        "FederalDieselTaxYear":"2016",
        "FederalDieselTax2":"No",
        "FederalDieselTaxRate2":"0",
        "FederalDieselTaxYear2":"2019",
        "FederalReimbursements":"96",
        "IndexHighwayCost":"No",
        "IndexConsumerPrice":"No",
        "IndexFuelEfficiency":"No",
        "IndexYear":"2019",
        "NetPercentIncreaseStateFuelTax":"75",
        "VehicleRegistrationFee":"Yes",
        "ChangedAllFee":"0",
        "ChangedMotorcycleFee":"0",
        "ChangedPassengerVehicleLess6000":"0",
        "ChangedTrailerLess6000":"0",
        "ChangedAllLess10k":"0",
        "ChangedAllLess18k":"0",
        "ChangedAllLess26k":"0",
        "ChangedAllLess40k":"0",
        "ChangedAllLess55k":"0",
        "ChangedAllLess70k":"0",
        "ChangedAllLess80k":"0",
        "ChangedYear":"2016",
        "VehicleRegistrationFee2":"No",
        "ChangedAllFee2":"0",
        "ChangedMotorcycleFee2":"0",
        "ChangedPassengerVehicleLess6000b":"0",
        "ChangedTrailerLess6000b":"0",
        "ChangedAllLess10k2":"0",
        "ChangedAllLess18k2":"0",
        "ChangedAllLess26k2":"0",
        "ChangedAllLess40k2":"0",
        "ChangedAllLess55k2":"0",
        "ChangedAllLess70k2":"0",
        "ChangedAllLess80k2":"0",
        "ChangedYear2":"2050",
        "VMTTax":"Yes",
        "VMTTaxFeePersonal":"5",
        "VMTTaxFeePersonalYear":"2016",
        "VMTTaxFeeCommercial":"0",
        "VMTTaxFeeCommercialYear":"2019",
        "StateGasTaxYearEnd":"2050",
        "StateDieselTaxYearEnd":"2050",
        "PercentOfMaintenance":"25",
        "PercentOfCategory2":"10.43",
        "PercentOfCategory3":"1.56",
        "PercentOfCategory5":"12.45",
        "PercentOfCategory7":"22.61",
        "PercentOfCategory9":"5.04",
        "PercentOfCategory11":"5.05",
        "MPO1":"No",
        "MPOList":"Abilene,Amarillo,Beaumont,Brownsville,Bryan-College Station,Austin,Corpus Christi,El Paso,Harlingen-San Benito,Hidalgo,Houston,Killeen-Temple,Laredo,Longview,Lubbock,Midland-Odessa,Dallas-Ft. Worth,San Angelo,San Antonio,Sherman-Denison,Texarkana,Tyler,Victoria,Waco,Wichita Falls",
        "MPO2":"No",
        "LocalGasTaxRate":"0",
        "LocalGasTaxYear":"2016",
        "LocalDieselTaxRate":"0",
        "LocalDieselTaxYear":"2016",
        "MPO3":"Yes",
        "LocalPersonalVMT":"1.4",
        "LocalCommercialVMT":"0",
        "LocalVMTYear":"2016",
        "MPO4":"No",
        "LocalAllFee":"0",
        "LocalMotorFee":"0",
        "LocalPassengerVehicleLT6k":"0",
        "LocalTrailerLT6k":"0",
        "LocalAllLess10k":"0",
        "LocalAllLess18k":"0",
        "LocalAllLess26k":"0",
        "LocalAllLess40k":"0",
        "LocalAllLess55k":"0",
        "LocalAllLess70k":"0",
        "LocalAllLess80k":"0",
        "LocalRegistrationYear":"2016",
        "MPO5":"Yes",
        "LocalFuelEfficiencyCommercial":"average",
        "LocalFuelEfficiencyPersonal":"average",
        "Proposition12":"Yes",
        "Proposition12Amount":"0",
        "Proposition12Years":"3",
        "Proposition12FirstYear":"2016",
        "Proposition14":"Yes",
        "Proposition14Amount":"0",
        "Proposition14Years":"3",
        "Proposition14FirstYear":"2016",
        "Proposition14YearPayback":"2016",
        "EIRateOfReturn":"8",
        "EIBusinessProfit":"4.6",
        "EISavingsRate":"10",
        //"ReportFormatting":"Graph.aspx?GraphName=AnnualBalance,Graph.aspx?GraphName=CummuBalance,SummaryToYear.aspx?EndYear=2030,SummaryToYear.aspx?EndYear=2035,SummaryToYear.aspx?EndYear=2040,DetailSummary.aspx,ShowFederalFuelTax.aspx",
        "advanced-mode-switch":true};

//Example of using the function
var calculatedData = getResults(Inputs);